### ISSUE TITLE
Future proofing against HDF-EOS changes

### ISSUE THREAD

**Issue by michaelleerilee** [SpatioTemporal/STAREmaster#102]
It seems HDF-EOS is fading, we don't people to get the idea that we are part of that shrinking pond.

Can we limit HDF-EOS dependencies, i.e. direct calls, and let some bigger fish like NetCDF give us those functions.

**Comment by captainkirk99** [comment]
Honestly, it's not going anywhere, so don't get your hopes up. ;-)

As mentioned in #107 once we handle some non-HDF4 datasets, we can have a version of STAREmaster that builds without HDF4 (and will then not have the capability to process HDF4 files.) So if HDF4 were to go away, that provides a natural path. Simply make building without HDF4 the default, and leave the capability for those that need it.

However, all MODIS data is in HDF4, and it seems that MODIS is a pretty important data set, and there's 20 years of great data. So although we have stopped designing new observation platforms that use HDF4, the MODIS platforms continue to function and continue to put out HDF4 data.

I couldn't find the L2 data we need in netCDF-4, but they do now release the higher-level MODIS products in netCDF-4, everyone's favorite format.

**Comment by michaelleerilee** [comment]
I agree HDF4 & HDF-EOS will be with us for quite a while.

**Comment by captainkirk99** [comment]
OK, I will close this issue. We already have #107 which we will add after we add a class for a dataset that does not require HDF4 (as all our classes currently do). 

When we handle some datasets that are not in HDF4, then anyone not interesting in HDF4 will be able to build STAREmaster, and will just get some to-be-added error code/message if they try to process a HDF4 file with a STAREmaster built without HDF4.

But, as noted, MODIS data will be with us for a long time. It's still coming in every day and it's beautiful. ;-) So HDF4 is a small price to pay.
