### ISSUE TITLE
Conditional compilation with OpenMP?

### ISSUE THREAD

**Issue by michaelleerilee** [SpatioTemporal/STAREmaster#106]
Do we need to add ifdef directives to block out OpenMP code on builds without OpenMP?

**Comment by captainkirk99** [comment]
Good question! Stand by and I will check.

**Comment by captainkirk99** [comment]
I believe I added what was necessary, because the test on a macos without OpenMP is working. So groovy.

But I actually thought I would have to do another step, so let me double-check before closing this issue.

**Comment by captainkirk99** [comment]
James does not want to use OpenMP in the Opendap build. So I will disable OpenMP by default, but still support it of --enable-openmp is used, and it is present on the build system.
