### ISSUE TITLE
staremaster segfaults with MOD09 for cover1 build

### ISSUE THREAD

**Issue by NiklasPhabian** [SpatioTemporal/STAREmaster#108]
createSidecarFile --data_type MOD09 --output_dir /download/MOD09 /down
load/MOD09/MYD09.A2020226.2105.006.2020228020450.hdf 
GeoFile constructor
ModisL2GeoFile constructor
Segmentation fault (core dumped)

**Comment by michaelleerilee** [comment]
Rilee: Create sidecarfile for MOD09, drive segfault.

**Comment by michaelleerilee** [comment]
Ran MOD09 large file test. Getting symptoms of memory problems. Not sure it's directly caused by STARE. Seems more like we're getting an allocation wrong somewhere.

**Comment by captainkirk99** [comment]
Can you try again with current master? I have cleaned up a lot of memory operations...

**Comment by captainkirk99** [comment]
I'm going to close this issue. The code has changed considerably since it was open. Try again with the current master.
