### ISSUE TITLE
cmake issues finding hdf4 and hdfeos2 libraries

### ISSUE THREAD

**Issue by captainkirk99** [SpatioTemporal/STAREmaster#6]
Niklas Griessbaum
Fri, Jul 24, 1:05 PM (19 hours ago)
to me

Hey Ed!

Time to revisit this. I am still not able to build the STAREMaster. If I understand correctly, you moved from autotools to cmake?

cmake now tells me :

-- STARE_LIBRARY="STARE_LIBRARY-NOTFOUND" ; STARE_INCLUDE_DIR="STARE_INCLUDE_DIR-NOTFOUND" 
fatal_error STARE library is required.

STARE.h lives at /usr/local/include/STARE.h on my system.
FindSTARE seems to have been looking for foo.h rather than STARE.h.
With this being corrected, cmake finds STARE, but still not HDFEOS2_INCLUDE_DIR

CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
HDFEOS2_INCLUDE_DIR

again, here my confusion about hdf5,4 and hdfeos kicks in. There seems to be a libhdfeos.a and libhdfeos.so living at I have a /usr/lib/x86_64-linux-gnu/. But we are looking for hdfeos2?

**Comment by michaelleerilee** [comment]
To build my STAREmaster, I used the following.
cmake -DCMAKE_BUILD_TYPE=Debug   -DCMAKE_INSTALL_PREFIX=/Users/mrilee/opt/local   -DNETCDF_INCLUDES=/Users/mrilee/opt/anaconda3/envs/develop/include   -DNETCDF_LIBRARIES=/Users/mrilee/opt/anaconda3/envs/develop/lib   -DSTARE_INCLUDE_DIR=/Users/mrilee/opt/local/include/STARE   -DSTARE_LIBRARY=/Users/mrilee/opt/local/lib   ../SM2-1
I also had to add the following to my SM2 CMakeLists.txt.
# STARE requires C++11add_compile_options( -std=c++11 )
Regarding HDFEOS2, I did have to install that as well.

**Comment by captainkirk99** [comment]
I don't need to add the -std=c++11 option. What error do you see without it?

**Comment by michaelleerilee** [comment]
The errors are below. This is using Conda Forge on MacOS 10.13.6.
> I don't need to add the -std=c++11 option. What error do you see without it?


(develop) twu4:SM2-2-BUILD mrilee$ make

Scanning dependencies of target ssc

[  8%] Building CXX object src/CMakeFiles/ssc.dir/SidecarFile.cpp.o

[ 16%] Building CXX object src/CMakeFiles/ssc.dir/GeoFile.cpp.o

[ 25%] Building CXX object src/CMakeFiles/ssc.dir/ModisL2GeoFile.cpp.o

In file included from /Users/mrilee/git/SM2-2/src/ModisL2GeoFile.cpp:10:

In file included from /Users/mrilee/opt/local/include/STARE/STARE.h:16:

In file included from /Users/mrilee/opt/local/include/STARE/HstmRange.h:9:

In file included from /Users/mrilee/opt/local/include/STARE/HtmRangeMultiLevel.h:16:

/Users/mrilee/opt/local/include/STARE/KeyPair.h:17:27: warning: in-class initialization of non-static data member is a C++11 extension [-Wc++11-extensions]

        Key lo; Key hi; bool set = false;

                                 ^

In file included from /Users/mrilee/git/SM2-2/src/ModisL2GeoFile.cpp:10:

In file included from /Users/mrilee/opt/local/include/STARE/STARE.h:16:

In file included from /Users/mrilee/opt/local/include/STARE/HstmRange.h:9:

In file included from /Users/mrilee/opt/local/include/STARE/HtmRangeMultiLevel.h:20:

/Users/mrilee/opt/local/include/STARE/EmbeddedLevelNameEncoding.h:227:31: warning: in-class initialization of non-static data member is a C++11 extension

      [-Wc++11-extensions]

  const uint32 topBitPosition = 63; //

[...]

In file included from /Users/mrilee/git/SM2-2/src/ModisL2GeoFile.cpp:10:

/Users/mrilee/opt/local/include/STARE/STARE.h:116:31: warning: in-class initialization of non-static data member is a C++11 extension [-Wc++11-extensions]

        uint64          search_level = STARE_HARDWIRED_RESOLUTION_LEVEL_MAX; /// Also known as max_level.

                                     ^

/Users/mrilee/opt/local/include/STARE/STARE.h:117:31: warning: in-class initialization of non-static data member is a C++11 extension [-Wc++11-extensions]

        uint64          build_level  = STARE_HARDWIRED_BUILD_LEVEL_MAX;  /// How deep to build the lookup table. Memory hog. Space vs. time...

                                     ^

39 warnings and 15 errors generated.

make[2]: *** [src/CMakeFiles/ssc.dir/ModisL2GeoFile.cpp.o] Error 1

make[1]: *** [src/CMakeFiles/ssc.dir/all] Error 2
make: *** [all] Error 2

(develop) twu4:SM2-2-BUILD mrilee$ g++ --version

Configured with: --prefix=/Aslan-1/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1

Apple LLVM version 10.0.0 (clang-1000.11.45.5)

Target: x86_64-apple-darwin17.7.0

Thread model: posix
InstalledDir: /Aslan-1/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Comment by captainkirk99** [comment]
OK, thanks, I will take a look...

**Comment by captainkirk99** [comment]
OK, the -std=c++11 has been added to the CMake build.
