### ISSUE TITLE
autotools build fail if HDF4 and HDFEOS are not built with -fPIC, and maybe if CXXFLAGS is not set to -std=c++11

### ISSUE THREAD

**Issue by jgallagher59701** [SpatioTemporal/STAREmaster#64]
Building with autotools, ./configure fails with:

```
checking STARE.h usability... no
checking STARE.h presence... yes
configure: WARNING: STARE.h: present but cannot be compiled
configure: WARNING: STARE.h:     check for missing prerequisite headers?
configure: WARNING: STARE.h: see the Autoconf documentation
configure: WARNING: STARE.h:     section "Present But Cannot Be Compiled"
configure: WARNING: STARE.h: proceeding with the compiler's result
configure: WARNING:     ## -------------------------------------------- ##
configure: WARNING:     ## Report this to edwardjameshartnett@gmail.com ##
configure: WARNING:     ## -------------------------------------------- ##
checking for STARE.h... no
checking whether STARE library is present... configure: error: STARE library not present.
edamame:STAREmaster jimg$ 
```

[config.log](https://github.com/SpatioTemporal/STAREmaster/files/5211529/config.log)

**Comment by captainkirk99** [comment]
Can you try setting CXXFLAGS to -std=c++11

`export CXXFLAGS='-std=c++11'
`
Then try again.

**Comment by jgallagher59701** [comment]
I get further, but now:

GeoFile.cpp:96:19: error: no matching function for call to 'SWopen'
    swathfileid = SWopen(fileName.c_str(), DFACC_RDONLY);

**Comment by jgallagher59701** [comment]
The library file for hdfeos is in the dir set with LDFLAGS and the header is in the dir set with CPPFLAGS. The library file is: 
libhdfeos.a and the headers are: HDFEOSVersion.h, HdfEosDef.h, .... The version info in the Version header is "HDFEOS Version: 2.19".

**Comment by captainkirk99** [comment]
OK, once again I need config.log. ;-)

**Comment by captainkirk99** [comment]
Here's an issue I've seen several times when building like this:

`autoreconf -i && CPPFLAGS="-I/usr/local/hdfeos/include -I/usr/local/hdf-4.2.15/include -I/usr/local/STARE-0.15.6/include -I/usr/local/netcdf-c-4.7.4_hdf5-1.10.6/include" LDFLAGS="-L/usr/local/hdfeos/lib -L/usr/local/hdf-4.2.15/lib -L/usr/local/STARE-0.15.6/lib -L/usr/local/netcdf-c-4.7.4_hdf5-1.10.6/lib" CXXFLAGS='-g -Wall' ./configure --enable-large-file-tests --with-large-test-files=/home/ed --enable-docs && make -j clean && make -j check

`
```
libtool: link: g++  -fPIC -DPIC -shared -nostdlib /usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/crti.o /usr/lib/gcc/x86_64-linux-gnu/9/crtbeginS.o  .libs/SidecarFile.o .libs/GeoFile.o .libs/ModisL2GeoFile.o .libs/NetcdfSidecarFile.o .libs/Modis09L2GeoFile.o .libs/Modis09GAGeoFile.o   -Wl,-rpath -Wl,/usr/local/hdf-4.2.15/lib -Wl,-rpath -Wl,/usr/local/netcdf-c-4.7.4_hdf5-1.10.6/lib -Wl,-rpath -Wl,/usr/local/hdf5-1.10.6/lib -Wl,-rpath -Wl,/usr/local/hdf-4.2.15/lib -Wl,-rpath -Wl,/usr/local/netcdf-c-4.7.4_hdf5-1.10.6/lib -Wl,-rpath -Wl,/usr/local/hdf5-1.10.6/lib -Wl,-rpath -Wl,/home/ed/Downloads/hdf-4.2.15/mfhdf/libsrc/.libs -Wl,-rpath -Wl,/home/ed/Downloads/hdf-4.2.15/hdf/src/.libs -L/usr/local/hdfeos/lib -L/usr/local/hdf-4.2.15/lib -L/usr/local/STARE-0.15.6/lib -L/usr/local/netcdf-c-4.7.4_hdf5-1.10.6/lib /usr/local/hdfeos/lib/libhdfeos.a /usr/local/hdf-4.2.15/lib/libmfhdf.so /usr/local/hdf-4.2.15/lib/libdf.so -ljpeg /usr/local/netcdf-c-4.7.4_hdf5-1.10.6/lib/libnetcdf.so -L/usr/local/hdf5-1.10.6/lib -L/usr/lib/x86_64-linux-gnu /usr/local/hdf5-1.10.6/lib/libhdf5_hl.so /usr/local/hdf5-1.10.6/lib/libhdf5.so -ldl -lz /usr/lib/x86_64-linux-gnu/libcurl.so -lSTARE -L/usr/lib/gcc/x86_64-linux-gnu/9 -L/usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu -L/usr/lib/gcc/x86_64-linux-gnu/9/../../../../lib -L/lib/x86_64-linux-gnu -L/lib/../lib -L/usr/lib/../lib -L/usr/lib/gcc/x86_64-linux-gnu/9/../../.. -lstdc++ -lm -lc -lgcc_s /usr/lib/gcc/x86_64-linux-gnu/9/crtendS.o /usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/crtn.o  -g   -pthread -Wl,-soname -Wl,libstaremaster.so.0 -o .libs/libstaremaster.so.0.0.0
/usr/bin/ld: /usr/local/hdfeos/lib/libhdfeos.a(SWapi.o): relocation R_X86_64_PC32 against symbol `SWXSwath' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:477: libstaremaster.la] Error 1
make[1]: Leaving directory '/home/ed/STAREmaster/src'
make: *** [Makefile:412: check-recursive] Error 1
(base) ed@mikado:~/STAREmaster$ 
```

**Comment by captainkirk99** [comment]
OK, @jgallagher59701 I'm confused by your build error. You are having a hard time with linking to SWopen(), yet the configure.ac contians:

`AC_SEARCH_LIBS([SWopen], [hdfeos], [], [AC_MSG_ERROR([hdfeos library required])])
`

So this means that SWopen is linked during configure, and if not working, the configure scripts errors out. So WTF?

Please post the config.log and if possible full output of configure and make.

**Comment by captainkirk99** [comment]
OK I am not confused by the error any more. ;-) When you see this: 

`can not be used when making a shared object; recompile with -fPIC
`

That is the clue. You need to rebuild hdfeos with CFLAGS=-fPIC. That's because it is not really capable of building shared libraries by itself. This library was coded before libtool was widely used, so shared libraries are not something it copes with. HDF4 is the same.

(BTW make sure you do a make clean as well, the build system is not smart enough to know that you changed a flag, so it will just reuse what it has built. And if you have installed hdf4 but forgotten to build it with --disable-netcdf, you must delete that install and rebuild and reinstall it, or else the netcdf.h file will remain, even if you rebuild and reinstall.)

**Comment by captainkirk99** [comment]
OK, last I heard you are having trouble building hdfeos. Here's how I build HDF4 and hdfeos. Start by deleting previous installs, especially install of hdf4, which will put a netcdf.h file into its include directory and mess up everything!

First I set CPPFLAGS and LDFLAGS:

```
      CPPFLAGS: "-I/usr/include -I/usr/local/include -I/home/runner/hdf4/include -I/home/runner/stare/include -I/home/runner/hdfeos2/include"
      LDFLAGS: "-L/home/runner/hdf4/lib -L/home/runner/stare/lib -L/home/runner/hdfeos2/lib"

```

Then build HDF4:

```
        wget https://support.hdfgroup.org/ftp/HDF/HDF_Current/src/hdf-4.2.13.tar.gz &> /dev/null
        tar zxf hdf-4.2.13.tar.gz
        cd hdf-4.2.13
        export CFLAGS=-fPIC
        ./configure --disable-netcdf --prefix=${PWD_DIR}/hdf4 
        make all 
        sudo make install clean
        cd ..

```
Then, to build hdfeos:

```
        wget https://observer.gsfc.nasa.gov/ftp/edhs/hdfeos/latest_release/HDF-EOS2.20v1.00.tar.Z  &> /dev/null
        tar zxf HDF-EOS2.20v1.00.tar.Z
        cd hdfeos
        CFLAGS=-fPIC ./configure  --enable-install-include --prefix=${PWD_DIR}/hdfeos2
        make
        sudo make install clean

```

These build instructions are from our autotools GitHub test workflow: https://github.com/SpatioTemporal/STAREmaster/blob/master/.github/workflows/autotools.yml

**Comment by captainkirk99** [comment]
I worked with James and we can now close this.

**Comment by captainkirk99** [comment]
Porting to the macOS for testing (see #24) I ran into even more trickiness with the HDF4 build. I have updated the README to contain the new magic incantations to get HDF4's old build system working with modern gcc.
