### ISSUE TITLE
handle adaptSpatialResolutionEstimatesInPlace()?

### ISSUE THREAD

**Issue by captainkirk99** [SpatioTemporal/STAREmaster#7]
Question from Niklas:

Kodi/James were adapting the STARE resolution bits according to the (scan-direction) distance to neighbors of the swath in compute_coordinates_resolution() of build_sidecar.cc. STARE itself has an according function adaptSpatialResolutionEstimatesInPlace(). Is this a feature that will be included in STAREMaster as well?

**Comment by michaelleerilee** [comment]
Take a look at my SM2 repository. I have implemented the in-place resolution adaptation.

**Comment by captainkirk99** [comment]
OK, I could not get your code to merge because I could not update it, but I ported it to new branches and everything works great. It's all merged to master now so I will close this issue.
