### ISSUE TITLE
Verify MOD09 labeling

### ISSUE THREAD

**Issue by michaelleerilee** [SpatioTemporal/STAREmaster#83]
MOD05 mislabeled geolocations as 1km instead of the actual 5km. We need to check MOD09 to make sure the labeling is correct.

**Comment by captainkirk99** [comment]
OK, so at issue here are the MOD09L2 files, described here: https://github.com/SpatioTemporal/STAREmaster/issues/42

**Comment by captainkirk99** [comment]
OK, taking a look with hdfview, to see what the original data files says. In the attributes for the lat/lon fields, it does say 1 km. Here's a screenshot:

![image](https://user-images.githubusercontent.com/37277297/95659501-bd4eaf00-0ade-11eb-8530-458f2fdc07ea.png)

We can also see that the field names have "1 km" in them, and the data fields also have an attribute:

 `Nadir Data Resolution = 1km`

![image](https://user-images.githubusercontent.com/37277297/95659539-fdae2d00-0ade-11eb-9173-a61e32f7b27e.png)

**Comment by captainkirk99** [comment]
@michaelleerilee can we close this issue?
