### ISSUE TITLE
Need examples of parsing granule metadata in C++

### ISSUE THREAD

**Issue by michaelleerilee** [SpatioTemporal/STAREmaster#84]
Constructing a cover is taking 2-3 minutes for MOD05_L2 because I'm using all points on the perimeter of the data array. This is overkill for a number of reasons. MOD05_L2 has GRING (geodesic ring) information in the EOS metadata. See GROUP=GRING therein. I've parsed this in Python--but it would be nice to do the following.

- Check a granule for GRING information
- If it exists, parse the GRING and extract the points to use as a perimeter for the cover.
- If it doesn't, use our existing calculation, possibly striding through the data with a stride greater than 1 (current stride is 1).

I do not currently know how to get the GRING info from the metadata using C++.  Shouldn't be too hard though.

_Originally posted by @michaelleerilee in https://github.com/SpatioTemporal/STAREmaster/issues/38#issuecomment-702163223_

**Comment by captainkirk99** [comment]
OK, so in the StructMetadata.0 metadata we have:

```
GROUP                  = GPOLYGON

    OBJECT                 = GPOLYGONCONTAINER
      CLASS                = "1"

      GROUP                  = GRING
        CLASS                = "1"

        OBJECT                 = EXCLUSIONGRINGFLAG
          NUM_VAL              = 1
          CLASS                = "1"
          VALUE                = "N"
        END_OBJECT             = EXCLUSIONGRINGFLAG

      END_GROUP              = GRING

      GROUP                  = GRINGPOINT
        CLASS                = "1"

        OBJECT                 = GRINGPOINTLONGITUDE
          NUM_VAL              = 4
          CLASS                = "1"
          VALUE                = (-171.348766580247, -145.694586768549, -151.705929561408, -173.673382552354)
        END_OBJECT             = GRINGPOINTLONGITUDE

        OBJECT                 = GRINGPOINTLATITUDE
          NUM_VAL              = 4
          CLASS                = "1"
          VALUE                = (37.5897944906235, 33.8625485332967, 16.3276616720112, 19.3618275007196)
        END_OBJECT             = GRINGPOINTLATITUDE

        OBJECT                 = GRINGPOINTSEQUENCENO
          NUM_VAL              = 4
          CLASS                = "1"
          VALUE                = (1, 2, 3, 4)
        END_OBJECT             = GRINGPOINTSEQUENCENO

      END_GROUP              = GRINGPOINT

    END_OBJECT             = GPOLYGONCONTAINER

  END_GROUP              = GPOLYGON

```

**Comment by michaelleerilee** [comment]
Looks like there are 4 corners in there as lon-lat pairs. We’ll have to extract those and call a hull routine.

**Comment by michaelleerilee** [comment]
We should detect and load the GRING information before we calculate the cover, and then switch between the perimeter-based and the GRING-based calculations.

**Comment by captainkirk99** [comment]
I am trying to find a way to do this with the hdfeos library.

Heres an interesting site with sample codes in many languages for many of these files. Unfortunately, they don't extract the StructMetadata. ;-) https://hdfeos.org/zoo/index_openLPDAAC_Examples.php#MOD

**Comment by captainkirk99** [comment]
From the HDF4 team:

> 
> I found a MODIS file that looks somewhat similar to the file you
> were looking at.
> 
> StructMetadata.0 is an SD attribute (with a huge value):
> 
> From "hdp dumpsds -h" on the file:
> 
> File name: MOD09GA.A2007268.h10v08.005.2007272184810.hdf
> 
> File attributes:
>           Attr0: Name = HDFEOSVersion
>                   Type = 8-bit signed char
>                   Count= 11
>                   Value = HDFEOS_V2.9
>           Attr1: Name = StructMetadata.0
>                   Type = 8-bit signed char
>                   Count= 32000
>                   Value = GROUP=SwathStructure\012END_GROUP=SwathSt
>                           ructure\012GROUP=GridStructure\012\011GRO
>                           UP=GRID_1\012\011\011GridName="MODIS_Grid
>                           _1km_2D"\012\011\011XDim=1200\012\011\011
>                           YDim=1200\012\011\011UpperLeftPointMtrs=(
> 
> It is stored as a Vdata. You can see that if using the "vshow" utility:
> 
> $ vshow MOD09GA.A2007268.h10v08.005.2007272184810.hdf + >& vshow.out
> [bljones@jelly ed]$ vi vshow.out
>    vg:32 <1965/1616> ne=10 (SolarAzimuth_c {Var0.0})
>    0 attributes.
>    vg:33 <1965/1622> ne=9 (gflags_c {Var0.0})
>    0 attributes.
>    vg:34 <1965/1628> ne=9 (orbit_pnt_c {Var0.0})
>    0 attributes.
>    vg:35 <1965/1634> ne=9 (nadd_obs_row_1km {Var0.0})
>    0 attributes.
>    vs:36 <1962/1635> nv=1 i=0 fld [VALUES] vsize=11 (HDFEOSVersion {Attr0.0})
> 0: fld [VALUES], type=4, order=11
> H D F E O S _ V 2 . 9
>   0 attributes.
>    vs:37 <1962/1636> nv=1 i=0 fld [VALUES] vsize=32000 (StructMetadata.0
> {Attr0.0})
> 0: fld [VALUES], type=4, order=32000
> G R O U P = S w a t h S t r u c t u r e
>   E N D _ G R O U P = S w a t h S t r u c t u r e
>   G R O U P = G r i d S t r u c t u r e
>           G R O U P = G R I D _ 1
>                   G r i d N a m e = " M O D I S _ G r i d _ 1 k m _ 2 D "
>                   X D i m = 1 2 0 0
>                   Y D i m = 1 2 0 0
> --- cut ---
> 
> I'll check with Kent and Joe to see if they have suggestions on tools
> to parse the blob of values.
> 
> -Barbara

**Comment by michaelleerilee** [comment]
I appreciate their help, but there always seems to be too much manual labor. I don't think we want STAREmaster calling CLI tools, if we can help it.

**Comment by captainkirk99** [comment]
No, of course not. I'm just recording the answer here so it doesn't get lost in my email. ;-)
