### ISSUE TITLE
Better error message: STAREmaster runs, produces no output and no error

### ISSUE THREAD

**Issue by NiklasPhabian** [SpatioTemporal/STAREmaster#87]
Running createSidecarFile invoked as follows produces the following feedback, but no sidecar file

griessbaum@xps:~/MOD09$ createSidecarFile -v MOD09.A2020187.1740.006.2020189022420.hdf 
GeoFile constructor
ModisL2GeoFile constructor
Reading HDF4 file MOD09.A2020187.1740.006.2020189022420.hdf with build level 5
nswath 1 MODIS SWATH TYPE L2

**Comment by michaelleerilee** [comment]
Does createSidecarFile infer the granule type from the name or metadata? I’ve always used a command line option. Something like -MOD09.

**Comment by captainkirk99** [comment]
You must use -d MOD09 as a command line option. 

Better error messaging in this case is required.

**Comment by NiklasPhabian** [comment]
alright, but then --data_type should not be an optional argument, but a mandatory one!
