### ISSUE TITLE
configure does not fine STARE.h

### ISSUE THREAD

**Issue by NiklasPhabian** [SpatioTemporal/STAREmaster#91]
on schiss (centos7), STARE.h lives at /usr/local/include/STARE.h, but .configure does not find it

checking for STARE.h... no
checking whether STARE library is present... configure: error: STARE library not present.

I tried setting 
export CPPFLAGS=" -I/usr/local/include" and
export LDFLAGS="-L/usr/local/lib"

which seems superfluous and did not change anything

**Comment by captainkirk99** [comment]
Can you try setting this as well, before running configure?

`export CXXFLAGS='-std=c++11'`

**Comment by NiklasPhabian** [comment]
that results in:

checking STARE.h usability... yes
checking STARE.h presence... no
configure: WARNING: STARE.h: accepted by the compiler, rejected by the preprocessor!
configure: WARNING: STARE.h: proceeding with the compiler's result
checking for STARE.h... yes
checking whether STARE library is present... yes
checking LIBS...  -lSTARE
checking for library containing nc_create... no
configure: error: Cannot link to the netcdf C library, set LDFLAGS.

**Comment by captainkirk99** [comment]
OK, sorry it took me so long to notice this reply. This means that setting the CXXFLAGS worked to allow configure to find stare.h, which is good.

Now it is breaking on linking to netCDF.

Here's the kind of command I use:

`autoreconf -i && CPPFLAGS="-I/usr/local/hdfeos2.19_fPIC/include -I/usr/local/hdf-4.2.15_fPIC/include -I/usr/local/STARE-0.16.3/include -I/usr/local/netcdf-c-4.7.4_hdf5-1.10.6/include" LDFLAGS="-L/usr/local/hdfeos2.19_fPIC/lib -L/usr/local/hdf-4.2.15_fPIC/lib -L/usr/local/STARE-0.16.3/lib -L/usr/local/netcdf-c-4.7.4_hdf5-1.10.6/lib" ./configure && make -j check`

Note that both my CPPFLAGS and my LDFLAGS include directories for HDFEOS2, HDF4, netCDF, and STARE. All four are required.

If you install all four in the same place, you only need to provide one include directory and one lib directory. If, like me, you have everything installed in different directories, then your CPPFLAGS must list all the includes, and your LDFLAGS must list all the lib directories.

If you can't get the build working, post here three things:
1 - your full build command 
2 - full output of autoreconf, configure, and make.
3 - attach the config.log file.

**Comment by captainkirk99** [comment]
Have we tried this again?

**Comment by NiklasPhabian** [comment]
alright. So the issue seems that despite the fact that I am pointing 
CPPFLAGS to /usr/local/hdfeos_fPIC/include (where I installed hdfeos from the fPIC built according to STAREmaster README) and LDFLAGS to /usr/local/hdfeos_fPIC/lib, configure seems to be using the 'system' libhdfeos.a, living at /usr/local/lib/

> 1 - your full build command
make -j check

> 2 - full output of autoreconf, 
None

> configure
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking how to print strings... printf
checking whether make supports the include directive... yes (GNU style)
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... gcc3
checking for a sed that does not truncate output... /usr/bin/sed
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for fgrep... /usr/bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking how to convert x86_64-pc-linux-gnu file names to x86_64-pc-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for a working dd... /usr/bin/dd
checking how to truncate binary pipes... /usr/bin/dd bs=4096 count=1
checking for mt... mt
checking if mt is a manifest tool... no
checking how to run the C preprocessor... gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking for gcc... (cached) gcc
checking whether we are using the GNU C compiler... (cached) yes
checking whether gcc accepts -g... (cached) yes
checking for gcc option to accept ISO C89... (cached) none needed
checking whether gcc understands -c and -o together... (cached) yes
checking dependency style of gcc... (cached) gcc3
checking for an ANSI C-conforming const... yes
checking how to run the C preprocessor... gcc -E
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking dependency style of g++... gcc3
checking how to run the C++ preprocessor... g++ -E
checking for ld used by g++... /usr/bin/ld -m elf_x86_64
checking if the linker (/usr/bin/ld -m elf_x86_64) is GNU ld... yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking for g++ option to produce PIC... -fPIC -DPIC
checking if g++ PIC flag -fPIC -DPIC works... yes
checking if g++ static flag -static works... yes
checking if g++ supports -c -o file.o... yes
checking if g++ supports -c -o file.o... (cached) yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... (cached) GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking for special C compiler options needed for large files... no
checking for _FILE_OFFSET_BITS value needed for large files... no
checking whether extra large files tests should be run (requires STAREmaster large test files)... no
checking where to find large test files... data
checking whether documentation should be build (requires doxygen)... no
checking for doxygen... doxygen
checking STARE.h usability... yes
checking STARE.h presence... yes
checking for STARE.h... yes
checking whether STARE library is present... yes
checking LIBS...  -lSTARE
checking for library containing nc_create... -lnetcdf
checking netcdf.h usability... yes
checking netcdf.h presence... yes
checking for netcdf.h... yes
checking for library containing H5Fopen... no
configure: WARNING: Can't find or link to the HDF5 C library; will build without HDF5 capability.
checking whether to use HDF5... no
checking mfhdf.h usability... yes
checking mfhdf.h presence... yes
checking for mfhdf.h... yes
checking hdf.h usability... yes
checking hdf.h presence... yes
checking for hdf.h... yes
checking for deflate in -lz... yes
checking for jpeg_set_quality in -ljpeg... yes
checking for Hclose in -ldf... yes
checking for NC_arrayfill in -lmfhdf... no
checking for library containing SDcreate... -lmfhdf
checking whether to use HDF4... yes
checking for library containing cos... -lm
checking for library containing SWopen... -lhdfeos
checking for HdfEosDef.h... yes
checking for ncdump... ncdump
checking for sed... /usr/bin/sed
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating test/run_large_file_tests.sh
config.status: creating Makefile
config.status: creating include/Makefile
config.status: creating src/Makefile
config.status: creating test/Makefile
config.status: creating test/data/Makefile
config.status: creating docs/Makefile
config.status: creating cmake/Makefile
config.status: creating config.h
config.status: config.h is unchanged
config.status: executing depfiles commands
config.status: executing libtool commands

> make
Making check in cmake
make[1]: Entering directory '/home/griessbaum/Dropbox/UCSB/STARE_Project/STAREmaster/cmake'
make[1]: Nothing to be done for 'check'.
make[1]: Leaving directory '/home/griessbaum/Dropbox/UCSB/STARE_Project/STAREmaster/cmake'
Making check in include
make[1]: Entering directory '/home/griessbaum/Dropbox/UCSB/STARE_Project/STAREmaster/include'
make[1]: Nothing to be done for 'check'.
make[1]: Leaving directory '/home/griessbaum/Dropbox/UCSB/STARE_Project/STAREmaster/include'
Making check in src
make[1]: Entering directory '/home/griessbaum/Dropbox/UCSB/STARE_Project/STAREmaster/src'
/bin/bash ../libtool  --tag=CXX   --mode=link g++  -g -O2   -o libstaremaster.la -rpath /usr/local/lib SidecarFile.lo GeoFile.lo ModisL2GeoFile.lo NetcdfSidecarFile.lo Modis09L2GeoFile.lo Modis09GAGeoFile.lo  -lhdfeos -lm -lmfhdf -ldf -ljpeg -lz -lnetcdf  -lSTARE
libtool: link: g++  -fPIC -DPIC -shared -nostdlib /usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/crti.o /usr/lib/gcc/x86_64-linux-gnu/9/crtbeginS.o  .libs/SidecarFile.o .libs/GeoFile.o .libs/ModisL2GeoFile.o .libs/NetcdfSidecarFile.o .libs/Modis09L2GeoFile.o .libs/Modis09GAGeoFile.o   -lhdfeos -lmfhdf -ldf -ljpeg -lz -lnetcdf -lSTARE -L/usr/lib/gcc/x86_64-linux-gnu/9 -L/usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu -L/usr/lib/gcc/x86_64-linux-gnu/9/../../../../lib -L/lib/x86_64-linux-gnu -L/lib/../lib -L/usr/lib/x86_64-linux-gnu -L/usr/lib/../lib -L/usr/lib/gcc/x86_64-linux-gnu/9/../../.. -lstdc++ -lm -lc -lgcc_s /usr/lib/gcc/x86_64-linux-gnu/9/crtendS.o /usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/crtn.o  -g -O2   -Wl,-soname -Wl,libstaremaster.so.0 -o .libs/libstaremaster.so.0.0.0
/usr/bin/ld: /usr/local/lib/libhdfeos.a(SWapi.o): relocation R_X86_64_PC32 against symbol `SWXSwath' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:477: libstaremaster.la] Error 1
make[1]: Leaving directory '/home/griessbaum/Dropbox/UCSB/STARE_Project/STAREmaster/src'
make: *** [Makefile:412: check-recursive] Error 1
[config.log](https://github.com/SpatioTemporal/STAREmaster/files/5475738/config.log)

**Comment by captainkirk99** [comment]
OK, well can you remove the non -fPIC version and try again?

**Comment by captainkirk99** [comment]
Is this issue still relevant?

There have been many changes in the build, but I think we found that the problem was that you must always link to an -fPIC version of both HDF4 and HDFEOS. This is annoying, but I don't think there is anything we can easily do about it.

**Comment by NiklasPhabian** [comment]
I won't get to verifying this very soon. You can close this. I will raise an issue if I have problems next time trying to build STAREMaster

**Comment by daltonkell** [comment]
Hi all, I ran into this issue when building. I looked at the `config.log` and saw that the error seemed to be that `STARE` had not been built with the proper flags - i.e. `-std=c++11`. I went back to the dependencies (I built separate libs for each) and re-compiled after setting `CXX_FLAGS="-std=c++11"` and `CXXFLAGS="-std=c++11"`. I then built `STARE` again, came back to `STAREmaster` and ensured the following:

```
CPPFLAGS="-I/home/dalton/SpatioTemporal/HDFEOS2/build/include/ -I/home/dalton/SpatioTemporal/HDF4/build/include/ -I/home/dalton/SpatioTemporal/STARE/build/include/ -I/usr/local/include/"
LDFLAGS="-L/home/dalton/SpatioTemporal/HDFEOS2/build/lib/ -L/home/dalton/SpatioTemporal/HDF4/build/lib -L/home/dalton/SpatioTemporal/STARE/build/lib/ -L/usr/local/lib/"
CXXFLAGS="-std=c++11"
CXX_FLAGS="-std=c++11"
```

I set the above `env` variables and then updated the `configure` script:

```
$ autoreconf -i --force
$ ./configure --prefix=/home/dalton/SpatioTemporal/STAREmaster/build/
```

and was able to successfully configure and make.
