### ISSUE TITLE
Installation: Change STARE_LIBRARY to STARE_LIB_DIRECTORY to reflect cmake convention.

### ISSUE THREAD

**Issue by michaelleerilee** [SpatioTemporal/STAREmaster#92]
Generally cmake is a little verbose and something like STARE_LIBRARY would actually refer to the library, i.e. libSTARE.a, not the directory.

**Comment by captainkirk99** [comment]
This is happening in cmake/FindSTARE.cmake.

I actually have no idea where this FindSTARE.cmake file came from. I'm pretty sure I didn't write it. ;-)

**Comment by captainkirk99** [comment]
OK, you know what, maybe I did write it, based on a template for a FindPackage that I found on-line.

**Comment by captainkirk99** [comment]
Well I also see this, which does not look right:

```
find_path(STARE_INCLUDE_DIR
  NAMES foo.h
  PATHS ${PC_STARE_INCLUDE_DIRS}
  PATH_SUFFIXES STARE
  )
find_library(STARE_LIBRARY
  NAMES foo
  PATHS ${PC_STARE_LIBRARY_DIRS}
  )

```

So this does look like something I put together based on a pattern I found on-line...
